name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t aristockij/wash-machine --push .

      - name: Deploy to VPS
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
        run: |
          # Настроим SSH для подключения
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_vpskey
          chmod 600 ~/.ssh/id_vpskey

          # Подключимся к серверу и перезапустим контейнер
          ssh -o StrictHostKeyChecking=no root@194.58.126.154 <<EOF
            cd /path/to/docker-compose/

            docker pull aristockij/wash-machine:latest &

            docker pull nginx:latest &
            wait

            docker-compose stop
            docker-compose up -d
            
          EOF

          rm -f ~/.ssh/id_vpskey
